name: Installing Grad-DFT and running tests

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      PYSCF_CONFIG_FILE: ".github/workflows/pyscf_conf.py"
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      - name: Install extra example dependencies
        run: |
          pip install -e ".[examples]"
      - name: Run unit tests
        run: |
            pytest -v tests/unit/test_eigenproblem.py
            pytest -v tests/unit/test_loss.py
      - name: Run integration tests
        run: |
          pytest -v tests/integration/molecules/test_non_xc_energy.py
          pytest -v tests/integration/molecules/test_functional_implementations.py
          pytest -v tests/integration/molecules/test_Harris.py
          pytest -v tests/integration/molecules/test_predict_B88.py
          pytest -v tests/integration/molecules/test_training.py
          pytest -v tests/integration/solids/test_training.py
          pytest -v tests/integration/solids/test_non_xc_energy.py


